apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-n3iwf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-n3iwf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-n3iwf
    spec:
      containers:      
      - name: myapp-container
        image: registry.gitlab.com/infinitydon/registry/free5gc-cpf:v3.0.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "./bin/n3iwf"]
        volumeMounts:
        - name: n3iwfcfg
          mountPath: /go/src/free5gc/config/n3iwfcfg.conf
          subPath: n3iwfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.168.2.11/24", "-g=172.16.223.19254"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: n3iwfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: n3iwfcfg.conf
            path: n3iwfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
      