apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-pcf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-pcf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-pcf
      #annotations:
         #diamanti.com/endpoint0: '{"endpointId":"pcf"}'

    spec:
      containers:      
      - name: myapp-container
        image: mjkota/free5gc-compose_free5gc-pcf
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        ports:
        - containerPort: 29507
        args: ["-c", "./pcf -pcfcfg ../config/pcfcfg.conf"]
        env:
          - name: GIN_MODE
            value: "release"
        volumeMounts:
        - name: pcfcfg
          mountPath: /free5gc/config/pcfcfg.conf
          subPath: pcfcfg.conf
        - name: free5gc
          mountPath: /free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: pcfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: pcfcfg.conf
            path: pcfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
---
kind: Service
apiVersion: v1
metadata:
  name: free5gc-pcf-service
spec:
  selector:
    app: free5gc-pcf
  ports:
  - protocol: TCP
    targetPort: 29507
    port: 29507
  clusterIP: None
 
