apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-webui-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-webui
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      containers:      
      - name: free5gc-webui-container
        image: mjkota/free5gc-compose_free5gc-webui
        imagePullPolicy: IfNotPresent
        command: ["./webui"]
        env:
          - name: GIN_MODE
            value: "release"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: webuicfg
          mountPath: free5gc/config/webuicfg.conf
          subPath: webuicfg.conf
        - name: free5gc
          mountPath: free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: webuicfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: webuicfg.conf
            path: webuicfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
---
kind: Service
apiVersion: v1
metadata:
  name: free5gc-webui-service
spec:
  selector:
    app: free5gc-webui
  ports:
  - protocol: TCP
    port: 5000
