apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: free5gc
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pod-service-endpoint-reader
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:serviceaccount:free5gc:mongo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-service-endpoint-reader
subjects:
  - kind: ServiceAccount
    name: mongo
    namespace: free5gc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: free5gc
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  #clusterIP: None
  type: NodePort 
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: free5gc-mongodb
  namespace: free5gc
spec:
  serviceName: "mongodb-svc"
  replicas: 1
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      serviceAccountName: mongo
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          command:
            - mongod
          args:
            #- "--replSet=rs0"
            - "--bind_ip=0.0.0.0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        #- name: mongo-sidecar
          #image: morphy/k8s-mongo-sidecar
          #imagePullPolicy: IfNotPresent
          #env:
            #- name: KUBERNETES_POD_LABELS
             # value: "role=mongo,environment=test"
            #- name: KUBERNETES_SERVICE_NAME
             # value: "mongodb-svc"
      volumes:
      - name: mongo-persistent-storage
        emptyDir: {}
